### PR TITLE
Subscription support in Makeradmin

### PR DESCRIPTION
**Pull request by agehall**
These changes allows members to activate subscriptions for both membership and lab access.

The code is largely event based and relies on webhooks from Stripe to actually trigger things. The stripe event handling has been extended to handle multiple relevant events due to this.

The subscription flow ensures that Makeradmin will create a customer object (if one doesn't exist!) for the Makerspace member and set the metadata keys `makerspace_user_id` and `makerspace_member_number` on the customer object. (These metadata keys will be set on most relevant objects related to subscriptions as well!). For now, the code uses email to find existing customer objects before creating a new one.

Once a customer object exists in Stripe, Makeradmin creates a Checkout Session that will, when completed return a SetupIntent with a valid payment method. Once the checkout session completes, events will capture this and assign the resulting payment method to the user as the default method for invoice payment.

If the user already has active membership or lab access when the subscription is started, this is handled via SubscriptionSchedules that causes the subscription to start about 1 day ahead of the current membership runs out. This ensures that the subscription doesn't run in parallel with existing time and just adds membership time over and over.

The integration monitors invoice events and whenever an invoice containing the relevant subscriptions is paid, Makeradmin will react and add time to the relevant membership.

There are several things missing before this can be officially used:

- UX improvements - I suck at UI so it needs a good polish, probably including a cleanup of the client code.
- User facing documentation and hints. It is currently not obvious how the subscription buttons work. (They are simple, but could use some tool tips)
- Pricing information before activation. One idea here is that instead of triggering the subscription flows directly from the member page we could have a separate subscription management page where we can present pricing and other relevant information.
- A way of managing and updating payment methods. It should be trivial to just run the Checkout Session part of the subscription flow which should accomplish this.
- Figure out how we want to actually get the Stripe price_id's for the two subscriptions (and any discounted versions thereof) into the system. Right now they are hardcoded `api/src/shop/stripe_checkout.py`.
- probably more

### CODE REVIEW

**Comment by HalfVoxel** [comment]
Amazing!

> For now, the code uses email to find existing customer objects before creating a new one.

This will fail if the user changes their email (which does happen at least a few times per year). I think it would be best to use the member id as the single source of truth.

> that causes the subscription to start about 1 day ahead of the current membership runs out. This ensures that the subscription doesn't run in parallel with existing time and just adds membership time over and over.

Doesn't this cause them to overlap by 1 day?

**Comment by HalfVoxel** [comment]
I think your PR has been rebased incorrectly btw. It shows a bunch of unrelated commits.

**Comment by agehall** [comment]
> > For now, the code uses email to find existing customer objects before creating a new one.
> 
> This will fail if the user changes their email (which does happen at least a few times per year). I think it would be best to use the member id as the single source of truth.

True - we can easily switch this to using member number instead. The customer lookup is centralized to a single function that expects a Member object...

> 
> > that causes the subscription to start about 1 day ahead of the current membership runs out. This ensures that the subscription doesn't run in parallel with existing time and just adds membership time over and over.
> 
> Doesn't this cause them to overlap by 1 day?

Sort of - it gives Stripe some slack when it comes to creating the invoice etc. If you have 10 days left of your membership and activate the subscription, it will be scheduled to start in 9 days at which point (assuming payment works) 1 year will be added to your membership. So you still get the right amount of membership, you just pay for it slightly early.


> I think your PR has been rebased incorrectly btw. It shows a bunch of unrelated commits.

Hmm, I wonder if that is because I rebased the branch onto master before beginning the work.

**Comment by emanuelen5** [comment]
You're merging into [makerspace:stripe-checkout-subscriptions](https://github.com/makerspace/makeradmin/tree/stripe-checkout-subscriptions), which is probably not rebased on master. So you're bringing lots of new commits into that branch.

**Comment by agehall** [comment]
Yeah, I started with that branch but had issues with it so I just rebased it onto master which might not have been the smartest thing.

What is the best way to clean this?

**Comment by emanuelen5** [comment]
Either merge into master instead, or rebase/merge the target branch onto master.

**Comment by agehall** [comment]
I’ll take a look at it today.

**Pull request closed without merging**
